import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import React, { PureComponent, useState } from 'react'

export interface AboutPageProps {}

export default function AboutPage(props: AboutPageProps) {
    const router = useRouter()
    const css = {
        r: 255,
        g: 0,
        b: 0,
        a: 0.3
    }
    const [fileUpload, setFileUpload] = useState('')

    const onUpload = (file: any) => {
        console.log('file', file);
        if (file && file.length > 0) {
            setFileUpload(URL.createObjectURL(file[0]))
        }
    }

    return (
        <>
            <Head>
                <title>User Detail Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div style = {{backgroundColor: `rgba(${css.r},${css.g},${css.b},${css.a})` }}>Thắng</div>
            
            <Link href={'/'}> 
                <a>GO Home</a>
            </Link>
            <div>
                <input type={'file'} onChange={(e) => onUpload(e.target.files)}></input>
            </div>
            <embed type="video/webm" src={fileUpload || ''} width="400" height="300"/>
            <div>
                <Image 
                    src={fileUpload || ''} 
                    alt='' 
                    width={100} 
                    height={100} 
                />
            </div>
        </>
    )
}
