import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { PureComponent } from 'react'

export interface AboutPageProps {}

export default function AboutPage(props: AboutPageProps) {
    const router = useRouter()
    const css = {
        r: 255,
        g: 0,
        b: 0,
        a: 0.3
    }
    console.log(router);
    
    return (
        <>
        <Head>
            <title>User Detail Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div style = {{backgroundColor: `rgba(${css.r},${css.g},${css.b},${css.a})` }}>Thắng</div>
        </>
    )
}
