import Head from 'next/head'
import Link from 'next/link'
import React, { PureComponent } from 'react'

export interface AboutPageProps {}

export default function AboutPage(props: AboutPageProps) {
    const css = {
        r: 255,
        g: 0,
        b: 0,
        a: 0.3
    }
    return (
        <>
            <Head>
                <title>User Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div style = {{backgroundColor: `rgba(${css.r},${css.g},${css.b},${css.a})` }}>User Page</div>
            <h1>
                Welcome <Link href="/user/detail/thang123">Thắng!</Link>
            </h1>
            <Link href={'/'}> 
                <a>GO Home</a>
            </Link>
        </>
    )
}
