import Head from "next/head";
import styles from '../styles/Intro.module.css'

export default function Intro(props) {
  return (
    <div>
      <Head>
        <title>Intro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <div className={styles.container}>
          <p className={styles.glitch}>
            <span aria-hidden="true">Intro</span>
            Intro
            <span aria-hidden="true">Intro</span>
          </p>
        </div>
      </div>
    </div>
  );
}
